In [1]:
# Import data analysis libraries
import pandas as pd
import numpy as np

### Import & Data Clean for ad_data

In [2]:
# Import the ad_data csv file and sense check the data
ad_data = pd.read_csv('./data/ad_data.csv')
ad_data

         ID  Bulkmail_ad  Twitter_ad  Instagram_ad  Facebook_ad  Brochure_ad
0      1826            0           0             0            0            0
1         1            0           0             0            0            1
2     10476            0           0             0            0            0
3      1386            0           0             0            0            0
4      5371            1           0             0            0            0
...     ...          ...         ...           ...          ...          ...
2211  10142            0           0             0            0            0
2212   5263            0           0             0            0            0
2213     22            0           0             0            0            0
2214    528            0           0             0            0            0
2215   4070            0           1             1            0            0

[2216 rows x 6 columns]

In [3]:
# Function for data sense check 
def sense_check(df):
    print('### Data Structure ###')
    df.info()
    
    print('\n' + '-'*50 + '\n')

    print('### Statistical Summary ###')
    print(df.describe())

    print('\n' + '-'*50 + '\n')

    print('### Duplicates ###')
    print(df.duplicated().sum())

In [4]:
sense_check(ad_data)

### Data Structure ###
<class 'pandas.DataFrame'>
RangeIndex: 2216 entries, 0 to 2215
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            2216 non-null   int64
 1   Bulkmail_ad   2216 non-null   int64
 2   Twitter_ad    2216 non-null   int64
 3   Instagram_ad  2216 non-null   int64
 4   Facebook_ad   2216 non-null   int64
 5   Brochure_ad   2216 non-null   int64
dtypes: int64(6)
memory usage: 104.0 KB

--------------------------------------------------

### Statistical Summary ###
                 ID  Bulkmail_ad   Twitter_ad  Instagram_ad  Facebook_ad  \
count   2216.000000  2216.000000  2216.000000   2216.000000  2216.000000
mean    5588.353339     0.073556     0.074007      0.073105     0.064079
std     3249.376275     0.261106     0.261842      0.260367     0.244950
min        0.000000     0.000000     0.000000      0.000000     0.000000
25%     2814.750000     0.000000     0.000000      0.000000     0.000000
50%     5458.500000     0.000000     0.000000      0.000000     0.000000
75%     8421.750000     0.000000     0.000000      0.000000     0.000000
max    11191.000000     1.000000     1.000000      1.000000     1.000000

       Brochure_ad
count  2216.000000
mean      0.013538
std       0.115588
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

--------------------------------------------------

### Duplicates ###
0

In [5]:
# Revise column names to lowercases
ad_clean = (
    ad_data
        .rename(columns={
    'ID': 'id',
    'Bulkmail_ad':'bulkmail',
    'Twitter_ad':'twitter',
    'Instagram_ad':'instagram',
    'Facebook_ad':'facebook',
    'Brochure_ad':'brochure'
        })
        .sort_values(by='id')
        .reset_index(drop=True)
)
# Confirm changes
ad_clean.head()

   id  bulkmail  twitter  instagram  facebook  brochure
0   0         0        0          0         0         0
1   1         0        0          0         0         1
2   9         0        0          0         0         0
3  13         0        0          0         0         0
4  17         0        0          0         0         0

In [6]:
# Save the DataFrame to a CSV file on computer
# ad_clean.to_csv("./data/ad_clean.csv", index=False)

# print("Success! Your CSV file has been created.")

### Import & Data Clean for ad_data

In [7]:
# Import the marketing_data csv file and sense check the data
md = pd.read_csv('./data/marketing_data.csv')
md

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,AmtLiq,...,AmtChocolates,AmtComm,NumDeals,NumWebBuy,NumWalkinPur,NumVisits,Response,Complain,Country,Count_success
0,1826,1971,Graduation,Divorced,"$84,835.00",0,0,6/16/14,0,189,...,189,218,1,4,6,1,1,0,SP,0
1,1,1962,Graduation,Single,"$57,091.00",0,0,6/15/14,0,464,...,0,37,1,7,7,5,1,0,CA,1
2,10476,1959,Graduation,Married,"$67,267.00",0,1,5/13/14,0,134,...,2,30,1,3,5,2,0,0,US,0
3,1386,1968,Graduation,Together,"$32,474.00",1,1,05/11/14,0,10,...,0,0,1,1,2,7,0,0,AUS,0
4,5371,1990,Graduation,Single,"$21,474.00",1,0,04/08/14,0,6,...,0,34,2,3,2,7,1,0,SP,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2211,10142,1977,PhD,Divorced,"$66,476.00",0,1,03/07/13,99,372,...,48,78,2,5,11,4,0,0,US,0
2212,5263,1978,2n Cycle,Married,"$31,056.00",1,0,1/22/13,99,5,...,8,16,1,1,3,8,0,0,SP,0
2213,22,1977,Graduation,Divorced,"$46,310.00",1,0,12/03/12,99,185,...,5,14,2,6,5,8,0,0,SP,0
2214,528,1979,Graduation,Married,"$65,819.00",0,0,11/29/12,99,267,...,165,63,1,5,10,3,0,0,IND,0
2215,4070,1970,PhD,Married,"$94,871.00",0,2,09/01/12,99,169,...,0,144,1,8,4,7,1,0,CA,2

In [8]:
sense_check(md)

### Data Structure ###
<class 'pandas.DataFrame'>
RangeIndex: 2216 entries, 0 to 2215
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              2216 non-null   int64
 1   Year_Birth      2216 non-null   int64
 2   Education       2216 non-null   str
 3   Marital_Status  2216 non-null   str
 4   Income          2216 non-null   str
 5   Kidhome         2216 non-null   int64
 6   Teenhome        2216 non-null   int64
 7   Dt_Customer     2216 non-null   str
 8   Recency         2216 non-null   int64
 9   AmtLiq          2216 non-null   int64
 10  AmtVege         2216 non-null   int64
 11  AmtNonVeg       2216 non-null   int64
 12  AmtPes          2216 non-null   int64
 13  AmtChocolates   2216 non-null   int64
 14  AmtComm         2216 non-null   int64
 15  NumDeals        2216 non-null   int64
 16  NumWebBuy       2216 non-null   int64
 17  NumWalkinPur    2216 non-null   int64
 18  NumVisits       2216 non-null   int64
 19  Response        2216 non-null   int64
 20  Complain        2216 non-null   int64
 21  Country         2216 non-null   str
 22  Count_success   2216 non-null   int64
dtypes: int64(18), str(5)
memory usage: 398.3 KB

--------------------------------------------------

### Statistical Summary ###
                 ID   Year_Birth      Kidhome     Teenhome      Recency  \
count   2216.000000  2216.000000  2216.000000  2216.000000  2216.000000
mean    5588.353339  1969.820397     0.441787     0.505415    49.012635
std     3249.376275    11.985554     0.536896     0.544181    28.948352
min        0.000000  1894.000000     0.000000     0.000000     0.000000
25%     2814.750000  1960.000000     0.000000     0.000000    24.000000
50%     5458.500000  1971.000000     0.000000     0.000000    49.000000
75%     8421.750000  1978.000000     1.000000     1.000000    74.000000
max    11191.000000  1997.000000     2.000000     2.000000    99.000000

            AmtLiq      AmtVege    AmtNonVeg       AmtPes  AmtChocolates  \
count  2216.000000  2216.000000  2216.000000  2216.000000    2216.000000
mean    305.091606    26.356047   166.995939    37.637635      27.028881
std     337.327920    39.793917   224.283273    54.752082      41.072046
min       0.000000     0.000000     0.000000     0.000000       0.000000
25%      24.000000     2.000000    16.000000     3.000000       1.000000
50%     174.500000     8.000000    68.000000    12.000000       8.000000
75%     505.000000    33.000000   232.250000    50.000000      33.000000
max    1493.000000   199.000000  1725.000000   259.000000     262.000000

           AmtComm     NumDeals    NumWebBuy  NumWalkinPur    NumVisits  \
count  2216.000000  2216.000000  2216.000000   2216.000000  2216.000000
mean     43.965253     2.323556     4.085289      5.800993     5.319043
std      51.815414     1.923716     2.740951      3.250785     2.425359
min       0.000000     0.000000     0.000000      0.000000     0.000000
25%       9.000000     1.000000     2.000000      3.000000     3.000000
50%      24.500000     2.000000     4.000000      5.000000     6.000000
75%      56.000000     3.000000     6.000000      8.000000     7.000000
max     321.000000    15.000000    27.000000     13.000000    20.000000

          Response     Complain  Count_success
count  2216.000000  2216.000000    2216.000000
mean      0.150271     0.009477       0.298285
std       0.357417     0.096907       0.679209
min       0.000000     0.000000       0.000000
25%       0.000000     0.000000       0.000000
50%       0.000000     0.000000       0.000000
75%       0.000000     0.000000       0.000000
max       1.000000     1.000000       4.000000

--------------------------------------------------

### Duplicates ###
0

In [9]:
# Revise marketing_data column names to lowercases
md_1 = (
    md
        .rename(columns={
            'ID':'id',
            'Kidhome':'kid_home',
            'Teenhome':'teen_home',
            'Dt_Customer':'registration_date',
            'AmtLiq':'amt_liquor',
            'AmtVege':'amt_vegetable',
            'AmtNonVeg':'amt_meat',
            'AmtPes':'amt_fish',
            'AmtChocolates':'amt_chocolate',
            'AmtComm':'amt_commodity',
            'NumDeals':'num_deals',
            'NumWebBuy':'num_web_purchase',
            'NumWalkinPur':'num_instore_purchase',
            'NumVisits':'web_visits_per_month',
            'Count_success':'lead_conversion'
        })
        .rename(columns=str.lower)
        .sort_values(by='id')
        .reset_index(drop=True)
)
# Confirm changes
md_1.head()

,id,year_birth,education,marital_status,income,kid_home,teen_home,registration_date,recency,amt_liquor,...,amt_chocolate,amt_commodity,num_deals,num_web_purchase,num_instore_purchase,web_visits_per_month,response,complain,country,lead_conversion
0,0,1986,Graduation,Married,"$70,951.00",0,0,05/04/13,66,239,...,87,54,1,3,9,1,0,0,SA,0
1,1,1962,Graduation,Single,"$57,091.00",0,0,6/15/14,0,464,...,0,37,1,7,7,5,1,0,CA,1
2,9,1976,Master,Single,"$46,098.00",1,1,8/18/12,86,57,...,0,36,4,3,2,8,0,0,CA,0
3,13,1948,PhD,Widow,"$25,358.00",0,1,7/22/13,57,19,...,0,8,2,1,3,6,0,0,SA,0
4,17,1972,PhD,Married,"$60,491.00",0,1,09/06/13,81,637,...,19,76,4,6,7,5,0,0,SP,0

In [10]:
# Writing a function to query for each series' unique value
def check_unique_values(df):
    for col in df.columns:
        print(f"Unique values in {col}:")
        print(df[col].unique())
        print("-" * 20)

In [11]:
check_unique_values(md_1)

Unique values in id:
[    0     1     9 ... 11187 11188 11191]
--------------------
Unique values in year_birth:
[1986 1962 1976 1948 1972 1966 1977 1961 1959 1988 1965 1971 1964 1973
 1954 1983 1970 1982 1989 1952 1967 1946 1978 1987 1981 1957 1947 1997
 1963 1949 1956 1980 1968 1953 1960 1974 1990 1969 1979 1958 1951 1975
 1955 1945 1992 1985 1950 1984 1993 1900 1944 1991 1994 1996 1995 1941
 1942 1901 1894]
--------------------
Unique values in education:
<StringArray>
['Graduation', 'Master', 'PhD', '2n Cycle', 'Basic']
Length: 5, dtype: str
--------------------
Unique values in marital_status:
<StringArray>
['Married', 'Single', 'Widow', 'Divorced', 'Together', 'Alone', 'YOLO',
 'Absurd']
Length: 8, dtype: str
--------------------
Unique values in income:
<StringArray>
[ '$70,951.00',  '$57,091.00',  '$46,098.00',  '$25,358.00',  '$60,491.00',
  '$46,891.00',  '$46,310.00',  '$17,144.00',  '$65,148.00',  '$25,545.00',
 ...
  '$70,713.00',  '$19,656.00',  '$19,419.00',  '$22,280.00',  '$49,678.00',
  '$65,968.00',  '$42,394.00', '$156,924.00',  '$26,487.00',  '$41,411.00']
Length: 1974, dtype: str
--------------------
Unique values in kid_home:
[0 1 2]
--------------------
Unique values in teen_home:
[0 1 2]
--------------------
Unique values in registration_date:
<StringArray>
['05/04/13',  '6/15/14',  '8/18/12',  '7/22/13', '09/06/13', '09/01/13',
 '12/03/12',  '2/15/14', '11/16/12', '09/08/12',
 ...
 '02/03/14', '11/08/13', '05/05/14', '08/05/12', '11/18/13', '12/27/12',
 '01/12/14', '12/26/12', '12/28/13',  '5/16/14']
Length: 662, dtype: str
--------------------
Unique values in recency:
[66  0 86 57 81 91 99 96  9 35 97 39 83  6 32 51 16 49 12 33 92 65 73 78
 29  3 59 93 40 62 55 21 54 47 98 90  8 60 76 71 11  4 31 74 30 48 75 13
 77 67 38 56 82  1 84 61 79 68 17 42 41 72 27 28 88 18 87 10  5 69 46 58
 80 63 64 24 36 53 34 25 95 94 26 43 70 44 85 52 23 45 50  7 15 20 89  2
 14 37 22 19]
--------------------
Unique values in amt_liquor:
[ 239  464   57   19  637   43  185   18  460   32  136    2  509   68
   14   34   15    0    5   11  275  544  215  466  760  345  206  656
   90  478  284   23  125  219  332 1288   35  556  138   24  279    1
   28  515  901  199  172  123  399   17  952   56  777  154  130    9
   95  182  493  918  330   29  235  198  462  158  229  373   47   91
  516  283 1170    6  315  374  534  294  308   67   27  824  102  792
  388 1060  434  322   25  908   13    3  174  267  941  163   31  398
  243  746  704  816  293  302  349   65  422   22  356   59   40  146
    4  972  707  162  787  141  529 1493   48   46  588  340  135  379
  584   12  167  151  508  962  784  561   63   97  303  320  381  306
   54 1099  411  410   38  224    7  254   20   16   51  139  121   87
   45  133  538  342  112  178  200  110  490  505  728   41  523  350
  600  299  557  532   70  258 1000  733  269 1486  938   85 1050  208
  520  755  124   50  979 1200   88   80  554 1253  384  690  483  587
  977  664  152  261  551  368  856 1076   33   10  407  496    8  280
  270  204  367  387   21  735  265  666   53  675  268   55   69  709
  347  741  120  966  558  171  547  292  184  577  408  354  890   66
  779 1459  213  796 1043  273  714   30 1259  100 1074  412  189 1148
  721  652   81  667  965  595  794  188   44  711  228  582  446  684
   78  522  867  619  372  563  896  377  450  997  448 1006  166  194
 1063  263  736  860  256 1218  353 1215  510  627  202  430   64  539
  625  623   39  778  177  173  376  823  364  362  789  531  526   26
  217  153  982  416  111 1016  691  495  424 1206  754  156  358  297
  519  375  543   72   52   71  295  181  536  366   62  864 1003  352
  763  196  626  453   60  444 1121 1067  104  934 1241  852  737  614
  751  305  175  437  717  291  530 1462  957   86  212  452  183  830
  317 1324  871  389 1492  249   96 1166  116  562  995  527   73  421
  879  712  244  129  726  815  635 1115 1045  629  919  390  157  216
  674 1039  255  676  583  251  159  122 1181  631  441  575  140   76
  492  750   94  594  371  488 1184  817 1035  403 1248  393  743  378
  105  473  533  231  192  571  359  642  897  639  960  801  186  618
  331  266  406  463  799   42  169  769  108  201  650  504 1004  517
  426  164  586 1001  822  910  580  107  507  325  881  913  702 1224
  240  459 1142  458  622  846  671 1315  247  457  365  203  386   61
   83 1394  889  227  383 1009  207  131  612   99  861  443  248   74
  391  689  176  456  555  574  753   58 1132   84 1379  606  106  680
  233  433  524 1193  252  756  264  425  420  445  380  670  479   37
  333  654 1047  774  738  298  128  576  489 1230  145  307   93  220
  471   36   79  983 1156 1111  238  758  729  454 1083  757  262  451
  316  545  572 1478 1020  502  513  338  848  309 1013  948  611  115
  402  560  899 1017  312  724  272  895  210  143  833  144  752  165
 1168 1171  546  986  313  191  499  703 1276  710  984  673 1311  324
  768  565  835  621  230  223  909  647  829  344  605  581  613  521
 1012  826  964  277  771  438  314   98  245  641  241  593 1285  518
 1073  783  537  109  739  604  888  432  953  205  395  686  209  722
  260  570  341  336  161  797  113  494  211 1332  958  928   77 1032
  218  197  940  820  179  967  620 1245  819  101  658  734  400  346
 1239  423  285  117 1023  482  318  428  863  447  134  980  329  795
  615 1296  351  127 1149 1298  800  296  301   75  132  155  392  514
  512  812  382  397  480  548  806  968  747  418  465  491 1205  825
   92  836 1349  925  525 1252  311  693 1048  688  328  274  630  415
  811  931  290  840 1279  221  559  944  236  882  603  920  335  357
 1103  708 1449  731  912  866  853  742  187  598  160  370  321  553
  610  503  168 1302 1308   89  440  180  369  847 1090  170  327 1126
  749  476  431  281  225  770  653  713  404  288  790  226  234  355
  992  597 1092  304   82 1396]
--------------------
Unique values in amt_vegetable:
[ 10   5   0  47  12   2  35   1   3  11   7   9  53  80  38  17 194  20
  14  83  23  31 133   4  19  30  74  70  21  61   6  27  90  65  56 112
  48  16  64 142  85  15  32  86 137  43  77 131   8 129  36  66  29  59
  13  44  81 124  28 103  72  60  88 105  55 190 144  39  41  25 117  84
  54  58  22  42  24  68  87 164 114  34  40 199  33  45 168  79  99  51
  50  63  76 172  37 104 111  69  97 115 122 107 100  26  71  75  89 120
  18  73 160 108 152 106 178 134 138 127  93 153  46 193 143 162  62 161
 102 185  91 197  96 155  49  67 181  92  82 151  98  57 154 183 149 140
 189 101 163 130 132 159 184 126 147 169 174 123 148 166]
--------------------
Unique values in amt_meat:
[ 554   64   27    5  237   23   88   19  422   12    6   65   16    3
  137   11   20   24    7   68  133   33  224  400  528   46  455   67
  193   55    2   52   60  377  613  717   38    8   29  181  345   57
  125  142   30  180  163   50   15   35  298  324  118  159  757   45
   43  179   71   83   94  449  151  320   31  116   47  218   80  162
   63  740  835   22  735  203   26  701  397  424  265  217  853  549
  131   78   74  238    1  329   93  913  250  204  153  356  454   59
   76  134   39   17  212   89   86  249  921  560  113   14   44  280
  215  109  114   54   48   18    4   99   69   25  421  164   91  112
   21  111   92  592  270  568   13  350  201  107  161  984  168  239
   36  495  278   85  843  537  322   82  223  562  267  143  899  110
  935  758  447  292  499  398  348  253  388  121  144  792  194  487
  103  266  160  115  445  460   81  241  569  183  303  124 1622  128
  157  689  206  672  240  622  171  812   77  981  311  100   61  149
  590   66   97  104  208  395  815  518  119  379  925  850  279  291
  243  122  768  801  586  257  932  260  384  101  540  535  414  951
   10   96  480  102  233  946  409  272  753  754  550   51  242  178
  459  184  425  420  300  135  123  351   41    9   28  255  214  625
   37   56  413  167  335  205  271  108  387  156  536  138  607   70
   87  382  127   72  750  230  207  106  132  687  374  864  678  612
   75   62  337  304  968  704  408  287  940   79  546  464  417   90
  797   73  363  594  129   53  338  505  323  567  309  364  573  426
   34  818  334  120  428  501  631  673  670  349  597  512  189  176
  314   49  430  166  883  234  170  333  375  553  252  155  780  117
  367  147  653  711  724   58  572  520  319  235  376  140  500   32
   40  352  655  473  635  491  305  595  708  685  389  523  145  152
  558  736   42  254  154  216  202  226  845   98 1725  974  392  650
  281  415  731  354  188  282  452  213  259  232  315  733  396  360
  199  697  510  898  431  915  141  790  385  649  175  403  497  432
  197   84  399  774  749  442  838  929  476  219  842  706  177  785
  185  601  746  450  359  158  186  747  561  435  380  139  391  599
  555  482  405  498  317  286  136  832  494  606  538  604  602  716
  713  742  629  674  341  591  263  209  172  275  849  559  534  614
  411  293  936  779  227  456  273  617  195  332  483  401  519  368
  651  547  196  761  786  222 1582  545  462  493  827  174  756  548
  297  471  342  690  469  732  288  603  530  470  514  231  961  575
  165  693  465  640  276  611  804  169  130  503  570  816  256  353
  274  228  813  639  419  444  565  509  126  873  247  507  269    0
  369  407  248  211  446  860  294   95  441  372  890  466  264  373
  522  295  751  654  182  221  694  410]
--------------------
Unique values in amt_fish:
[254   7   0  12  29  15  33  16   4 179  26   6  19   3  25  23 119  17
  98  52 110 149  80 210  32  75  20  21  71  47   2 162 146  13  36 186
   8 123  10  86  51  42  11  84 164 102  67  91  45  40  76  27 138  85
 120 216  46  38  69  97  63 112  24 258 168  50  60  39  34  28 147  37
  30  62 193 237 182  49  61 104  64 130 205  55  58 175 227 181 189 172
  89 234 106 223 224 246 207 151  48 167 177 116  41 111  94  54 127 150
 208 180 250  73  99  59 225 219  90 159 156 121  43  95 124 158 169  56
 141  93 160  65 103 134 188  78 145 101 153 128  72 108 198 171   1 192
 115 125 242 199 142 220 132 185 202 136 197 129 133 232 247 253 201 184
 173   5  77 114  82 140  44 229 212 259 240  68 137  35  81 218 166 231
  31 194]
--------------------
Unique values in amt_chocolate:
[ 87   0  19  15   5   2  12   3   1  11  61   8  14   7 151  49  93  75
 107  36   6   9 125  95  31  21  13  44   4  51 149  40  10  27 163 103
  33  72  32  25  58  45  20 137 194  24 165  65  74  26  66  59  46  17
  30  43  57  28  91  38 176 147 109 195  22 133  47  37 172 156  64  42
  71  41 102  84  54  48  29  16  60 153 188 150 160  68 105 175  82  23
 122  69 148  92 189  18  83  96 129 196  86  34 192  98 112  56  81 116
  80  73  35 138  85 118 126  53  97 143  89  39  78  63  79 108  55 134
 182 101  88 185  67  76 130  94 174  50 161 152 167 115 111 127 132 262
 123 121 169 187 178 144 113 146  77 145 128 120  70 136 162 157 142 191
  62 114  99 198 179 106 197 110 173 124 139 141 100 166]
--------------------
Unique values in amt_commodity:
[ 54  37  36   8  76  61  14   6 153  85  32   9   5   1  45  17  21  20
   7 107  13  99   0  12  97  93  67 117  52   2  30  57  27  43  59  34
  47  95 191  16  88  25 122 116  84  26   4 125  19 120  28 192  91  64
  41 151 118  80  24 101  42   3  46  63 176  33  53 111  35  65 110  15
  70 106  48  73  92  56  98 177 134  22  18  49  29  31  71  44 145 124
 169 133  10  66 185  38 112  11 224 147 241 130  68  74 174 203 173 232
 170  77 172  81 128 103 126  89  51 138 215  39 157 129 218  23 108  83
  69 121 205 168  86 183 149 146  50 150 175  75 152  82  55  96  58 154
  40 210 144 160 166  79  60 199 143 161 131 162 200 219 195 159 114 262
 163 227 178 109 182 165  90 207 223 204 115 229 102 155 140 171 132 158
 135  72  78 187 231 139 123 233 100 291 190 142 198 242 127 248  62 246
 245 141 196 180  94 197 119 181 148 137 321 247 249 216]
--------------------
Unique values in num_deals:
[ 1  4  2  5  3  6  0 15  7 11  8  9 10 13 12]
--------------------
Unique values in num_web_purchase:
[ 3  7  1  6  2  4  0  8  5  9 11 10 27 23 25]
--------------------
Unique values in num_instore_purchase:
[ 9  7  2  3  4  5  8 11  6 10 13 12  1  0]
--------------------
Unique values in web_visits_per_month:
[ 1  5  8  6  4  7  2  3  9  0 14 17 20 10 13 19]
--------------------
Unique values in response:
[0 1]
--------------------
Unique values in complain:
[0 1]
--------------------
Unique values in country:
<StringArray>
['SA', 'CA', 'SP', 'GER', 'IND', 'US', 'AUS', 'ME']
Length: 8, dtype: str
--------------------
Unique values in lead_conversion:
[0 1 2 4 3]
--------------------

In [12]:
# Removing symbols from the income column values and converting it to an int data type
md_1['income'] = (
    md_1['income']
    .str.replace(r'[^\w\s]', '', regex=True)
    .astype(int)
)
print(md_1['income'].dtype)
md_1.head()

int64

,id,year_birth,education,marital_status,income,kid_home,teen_home,registration_date,recency,amt_liquor,...,amt_chocolate,amt_commodity,num_deals,num_web_purchase,num_instore_purchase,web_visits_per_month,response,complain,country,lead_conversion
0,0,1986,Graduation,Married,7095100,0,0,05/04/13,66,239,...,87,54,1,3,9,1,0,0,SA,0
1,1,1962,Graduation,Single,5709100,0,0,6/15/14,0,464,...,0,37,1,7,7,5,1,0,CA,1
2,9,1976,Master,Single,4609800,1,1,8/18/12,86,57,...,0,36,4,3,2,8,0,0,CA,0
3,13,1948,PhD,Widow,2535800,0,1,7/22/13,57,19,...,0,8,2,1,3,6,0,0,SA,0
4,17,1972,PhD,Married,6049100,0,1,09/06/13,81,637,...,19,76,4,6,7,5,0,0,SP,0

In [13]:
# Standardize the education column values
# Define the new category labels
education_categories = {
    'Basic':'High School / Below',
    'Graduation':'Bachelor',
    'Master':'Master',
    '2n Cycle':'Master',
    'PhD':'Doctorate'
}

# Map old values to new values
md_1['education'] = md_1['education'].map(education_categories)

# View changes
md_1['education'].unique()

<StringArray>
['Bachelor', 'Master', 'Doctorate', 'High School / Below']
Length: 4, dtype: str

In [14]:
# Standardize the marital status column values
# Define the new marital status category labels
marital_categories = {
    'Single':'Single',
    'Widow':'Single',
    'Divorced':'Single',
    'Alone':'Single',
    'Married':'Couple',
    'Together':'Couple',
    'YOLO':'Other',
    'Absurd':'Other'
}

# Map old values to new values
md_1['marital_status'] = md_1['marital_status'].map(marital_categories)

# View changes
md_1['marital_status'].unique()

<StringArray>
['Couple', 'Single', 'Other']
Length: 3, dtype: str

In [15]:
# Review the number of Other values
# If the number is small, we can consider removing it from the dataset
print((md_1['marital_status'] == 'Other').sum())

4

In [18]:
# Create a new dataframe without the Other value in marital status
md_2 = md_1[md_1['marital_status'] != 'Other'].copy()

# View changes
print(md_2['marital_status'].unique())
print('\n' + '-'*50 + '\n')
md_2

<StringArray>
['Couple', 'Single']
Length: 2, dtype: str

--------------------------------------------------

,id,year_birth,education,marital_status,income,kid_home,teen_home,registration_date,recency,amt_liquor,...,amt_chocolate,amt_commodity,num_deals,num_web_purchase,num_instore_purchase,web_visits_per_month,response,complain,country,lead_conversion
0,0,1986,Bachelor,Couple,7095100,0,0,05/04/13,66,239,...,87,54,1,3,9,1,0,0,SA,0
1,1,1962,Bachelor,Single,5709100,0,0,6/15/14,0,464,...,0,37,1,7,7,5,1,0,CA,1
2,9,1976,Master,Single,4609800,1,1,8/18/12,86,57,...,0,36,4,3,2,8,0,0,CA,0
3,13,1948,Doctorate,Single,2535800,0,1,7/22/13,57,19,...,0,8,2,1,3,6,0,0,SA,0
4,17,1972,Doctorate,Couple,6049100,0,1,09/06/13,81,637,...,19,76,4,6,7,5,0,0,SP,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2211,11178,1973,Master,Single,4239400,1,0,3/23/14,69,15,...,1,4,1,1,3,7,0,0,GER,0
2212,11181,1950,Doctorate,Couple,15692400,0,0,8/29/13,85,2,...,1,1,0,0,0,0,0,0,CA,0
2213,11187,1979,High School / Below,Single,2648700,1,0,5/20/13,23,2,...,14,23,3,2,3,5,0,0,CA,0
2214,11188,1958,Bachelor,Couple,2609100,1,1,2/25/14,84,15,...,17,20,3,2,3,5,0,0,SP,0
2215,11191,1987,Bachelor,Single,4141100,0,0,12/07/13,11,37,...,3,18,1,2,4,6,0,0,SP,0

In [17]:
# Save the DataFrame to a CSV file on computer
# md_1.to_csv("./data/md_1.csv", index=False)

# print("Success! Your CSV file has been created.")